# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importVersion.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_importVersionDialog(object):
    def setupUi(self, importVersionDialog):
        importVersionDialog.setObjectName("importVersionDialog")
        importVersionDialog.resize(323, 148)
        importVersionDialog.setStyleSheet("*{\n"
"    \n"
"border:none;\n"
"background-color:transparent;\n"
"background:none;\n"
"padding:0;\n"
"margin:0;\n"
"color:#fff;\n"
"}\n"
"\n"
"\n"
"\n"
"#centralwidget{\n"
"background-color:#1f232a;\n"
"}\n"
"\n"
"QPushButton{\n"
"text-align:left;\n"
"padding: 5px 10px;\n"
"\n"
"border-top-left-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"text-align:left;\n"
"padding:2px 10px;\n"
"color:white;}")
        self.centralwidget = QtWidgets.QWidget(importVersionDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("#frame{border:2px solid grey; border-radius:15px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"\n"
"QLineEdit {\n"
"    background-color: #cccccc;\n"
"    border-radius: 20px; \n"
"\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.import_button = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.import_button.setFont(font)
        self.import_button.setStyleSheet("border: 2px solid grey;\n"
"border-radius:15px;\n"
"text-align:center;")
        self.import_button.setObjectName("import_button")
        self.gridLayout_2.addWidget(self.import_button, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        importVersionDialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(importVersionDialog)
        QtCore.QMetaObject.connectSlotsByName(importVersionDialog)

    def retranslateUi(self, importVersionDialog):
        _translate = QtCore.QCoreApplication.translate
        importVersionDialog.setWindowTitle(_translate("importVersionDialog", "MainWindow"))
        self.checkBox.setText(_translate("importVersionDialog", "Remove Previous Data"))
        self.import_button.setText(_translate("importVersionDialog", "Import"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    importVersionDialog = QtWidgets.QMainWindow()
    ui = Ui_importVersionDialog()
    ui.setupUi(importVersionDialog)
    importVersionDialog.show()
    sys.exit(app.exec_())
