# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoMatchingResultPopwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoMatchineResultPopWindow(object):
    def setupUi(self, NoMatchineResultPopWindow):
        NoMatchineResultPopWindow.setObjectName("NoMatchineResultPopWindow")
        NoMatchineResultPopWindow.resize(592, 143)
        NoMatchineResultPopWindow.setStyleSheet("*{\n"
"    \n"
"border:none;\n"
"background-color:transparent;\n"
"background:none;\n"
"padding:0;\n"
"margin:0;\n"
"color:#fff;\n"
"}\n"
"\n"
"\n"
"\n"
"#centralwidget{\n"
"background-color:#1f232a;\n"
"}\n"
"#EditVendor{\n"
"background-color:#16191d;\n"
"}\n"
"QPushButton{\n"
"text-align:left;\n"
"padding: 5px 10px;\n"
"\n"
"border-top-left-radius:5px;\n"
"border-botton-left-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"text-align:left;\n"
"padding:2px 10px;\n"
"color:white;}")
        self.centralwidget = QtWidgets.QWidget(NoMatchineResultPopWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #0000FF; /* 鼠标悬停时的背景颜色为蓝色 */\n"
"    color: #FFFFFF; /* 鼠标悬停时的文字颜色为白色 */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        NoMatchineResultPopWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(NoMatchineResultPopWindow)
        QtCore.QMetaObject.connectSlotsByName(NoMatchineResultPopWindow)

    def retranslateUi(self, NoMatchineResultPopWindow):
        _translate = QtCore.QCoreApplication.translate
        NoMatchineResultPopWindow.setWindowTitle(_translate("NoMatchineResultPopWindow", "NoMatchineResultPopWindow"))
        self.label.setText(_translate("NoMatchineResultPopWindow", "No matching result found, please try again"))
        self.pushButton.setText(_translate("NoMatchineResultPopWindow", "Back"))
