# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RemoveVendorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_remove(object):
    def setupUi(self, Dialog_remove):
        Dialog_remove.setObjectName("Dialog_remove")
        Dialog_remove.resize(399, 100)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_remove)
        self.buttonBox.setGeometry(QtCore.QRect(200, 51, 191, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog_remove)
        self.label.setGeometry(QtCore.QRect(10, 10, 371, 51))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_remove)
        self.buttonBox.accepted.connect(Dialog_remove.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_remove.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_remove)

    def retranslateUi(self, Dialog_remove):
        _translate = QtCore.QCoreApplication.translate
        Dialog_remove.setWindowTitle(_translate("Dialog_remove", "Dialog"))
        self.label.setText(_translate("Dialog_remove", "Are you sure you want to remove this vendor?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_remove = QtWidgets.QDialog()
    ui = Ui_Dialog_remove()
    ui.setupUi(Dialog_remove)
    Dialog_remove.show()
    sys.exit(app.exec_())
