# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 583)
        MainWindow.setStyleSheet("*{\n"
"    \n"
"border:none;\n"
"background-color:transparent;\n"
"background:none;\n"
"padding:0;\n"
"margin:0;\n"
"color:#fff;\n"
"}\n"
"\n"
"\n"
"\n"
"#centralwidget{\n"
"background-color:#1f232a;\n"
"}\n"
"#EditVendor{\n"
"background-color:#16191d;\n"
"}\n"
"QPushButton{\n"
"text-align:left;\n"
"padding: 5px 10px;\n"
"\n"
"border-top-left-radius:5px;\n"
"border-botton-left-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"text-align:left;\n"
"padding:2px 10px;\n"
"color:white;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchImage_frame = QtWidgets.QFrame(self.centralwidget)
        self.SearchImage_frame.setGeometry(QtCore.QRect(750, 30, 151, 141))
        self.SearchImage_frame.setStyleSheet("image: url(:/image/R.png);")
        self.SearchImage_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SearchImage_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SearchImage_frame.setObjectName("SearchImage_frame")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 130, 721, 431))
        self.frame.setStyleSheet("border: 5px solid rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(20, 30, 681, 361))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    color: black; /* QComboBox中的文本颜色为黑色 */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: black; /* 下拉列表中的文本颜色为黑色 */\n"
"}\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    color: black; /* QComboBox中的文本颜色为黑色 */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: black; /* 下拉列表中的文本颜色为黑色 */\n"
"}\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setStyleSheet("QSpinBox {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.spinBox_2.setMaximum(9999)
        self.spinBox_2.setProperty("value", 2024)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("QSpinBox {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.spinBox.setMinimum(0)
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    color: black; /* QComboBox中的文本颜色为黑色 */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: black; /* 下拉列表中的文本颜色为黑色 */\n"
"}\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStatusTip("")
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 2, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 30, 137, 23))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(770, 410, 145, 161))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton:hover {\n"
"    background-color: #0000FF; /* 鼠标悬停时的背景颜色为蓝色 */\n"
"    color: #FFFFFF; /* 鼠标悬停时的文字颜色为白色 */\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton:hover {\n"
"    background-color: #0000FF; /* 鼠标悬停时的背景颜色为蓝色 */\n"
"    color: #FFFFFF; /* 鼠标悬停时的文字颜色为白色 */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #0000FF; /* 鼠标悬停时的背景颜色为蓝色 */\n"
"    color: #FFFFFF; /* 鼠标悬停时的文字颜色为白色 */\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Downloads/system-regular-42-search.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(780, 280, 125, 71))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Search"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Title Substring"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Issn"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Isbn"))
        self.comboBox.setItemText(0, _translate("MainWindow", "DR"))
        self.comboBox.setItemText(1, _translate("MainWindow", "DR_D1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "DR_D2"))
        self.comboBox.setItemText(3, _translate("MainWindow", "IR"))
        self.comboBox.setItemText(4, _translate("MainWindow", "IR_A1"))
        self.comboBox.setItemText(5, _translate("MainWindow", "IR_M1"))
        self.comboBox.setItemText(6, _translate("MainWindow", "PR"))
        self.comboBox.setItemText(7, _translate("MainWindow", "PR_P1"))
        self.comboBox.setItemText(8, _translate("MainWindow", "TR"))
        self.comboBox.setItemText(9, _translate("MainWindow", "TR_B1"))
        self.comboBox.setItemText(10, _translate("MainWindow", "TR_B2"))
        self.comboBox.setItemText(11, _translate("MainWindow", "TR_B3"))
        self.comboBox.setItemText(12, _translate("MainWindow", "TR_J1"))
        self.comboBox.setItemText(13, _translate("MainWindow", "TR_J2"))
        self.comboBox.setItemText(14, _translate("MainWindow", "TR_J3"))
        self.comboBox.setItemText(15, _translate("MainWindow", "TR_J4"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Please input the tile/issn/isbn in correct format"))
        self.label_3.setText(_translate("MainWindow", "Title Search Option"))
        self.label_2.setText(_translate("MainWindow", "Report type"))
        self.label_5.setText(_translate("MainWindow", "End Year"))
        self.label_4.setText(_translate("MainWindow", "Start Year"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Data Base"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Publisher id"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Publisher"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Platform"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Proprietary_id"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Data_type"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Access_method"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Metric_type"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Vendor"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "January"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "February"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "March"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "April"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "May"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "June"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "July"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "August"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "September"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "October"))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "November"))
        self.comboBox_3.setItemText(20, _translate("MainWindow", "December"))
        self.label_6.setText(_translate("MainWindow", "Detailed Search Option"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Please enter the appropriate name"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Search</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Import Search"))
        self.pushButton_2.setText(_translate("MainWindow", "Export Search"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.checkBox.setText(_translate("MainWindow", "Open File"))
        self.checkBox_2.setText(_translate("MainWindow", "Open Folder"))
import Search_image_rc
