# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 615)
        MainWindow.setStyleSheet("*{\n"
"    \n"
"border:none;\n"
"background-color:transparent;\n"
"background:none;\n"
"padding:0;\n"
"margin:0;\n"
"color:#fff;\n"
"}\n"
"\n"
"\n"
"\n"
"#centralwidget{\n"
"background-color:#1f232a;\n"
"}\n"
"#EditVendor{\n"
"background-color:#16191d;\n"
"}\n"
"QPushButton{\n"
"text-align:left;\n"
"padding: 5px 10px;\n"
"\n"
"border-top-left-radius:5px;\n"
"border-botton-left-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"text-align:left;\n"
"padding:2px 10px;\n"
"color:white;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(720, 10, 201, 131))
        self.frame.setStyleSheet("image:url(:/image/png-configuration.png)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(40, 120, 671, 471))
        self.frame_2.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border: 5px solid")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(10, 14, 651, 441))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QToolTip {\n"
"    color: black; /* 工具提示文本颜色为黑色 */\n"
"    background-color: #FFFFE0; /* 工具提示背景颜色，可以根据需要进行更改 */\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    color: black; /* QComboBox中的文本颜色为黑色 */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: black; /* 下拉列表中的文本颜色为黑色 */\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton:hover {\n"
"    background-color: #0000FF; /* 鼠标悬停时的背景颜色为蓝色 */\n"
"    color: #FFFFFF; /* 鼠标悬停时的文字颜色为白色 */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton:hover {\n"
"    background-color: #0000FF; /* 鼠标悬停时的背景颜色为蓝色 */\n"
"    color: #FFFFFF; /* 鼠标悬停时的文字颜色为白色 */\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QToolTip {\n"
"    color: black; /* 工具提示文本颜色为黑色 */\n"
"    background-color: #FFFFE0; /* 工具提示背景颜色，可以根据需要进行更改 */\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QToolTip {\n"
"    color: black; /* 工具提示文本颜色为黑色 */\n"
"    background-color: #FFFFE0; /* 工具提示背景颜色，可以根据需要进行更改 */\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QToolTip {\n"
"    color: black; /* 工具提示文本颜色为黑色 */\n"
"    background-color: #FFFFE0; /* 工具提示背景颜色，可以根据需要进行更改 */\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QToolTip {\n"
"    color: black; /* 工具提示文本颜色为黑色 */\n"
"    background-color: #FFFFE0; /* 工具提示背景颜色，可以根据需要进行更改 */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QToolTip {\n"
"    color: black; /* 工具提示文本颜色为黑色 */\n"
"    background-color: #FFFFE0; /* 工具提示背景颜色，可以根据需要进行更改 */\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 6, 1, 1, 3)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QToolTip {\n"
"    color: black; /* 工具提示文本颜色为黑色 */\n"
"    background-color: #FFFFE0; /* 工具提示背景颜色，可以根据需要进行更改 */\n"
"}\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 7, 0, 1, 4)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStatusTip("")
        self.label_8.setStyleSheet("QToolTip {\n"
"    color: black; /* 工具提示文本颜色为黑色 */\n"
"    background-color: #FFFFE0; /* 工具提示背景颜色，可以根据需要进行更改 */\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 3)
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setStyleSheet("QSpinBox {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.spinBox_4.setMaximum(9999)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 2, 1, 1, 3)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setStyleSheet("QSpinBox {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.spinBox_3.setMaximum(9999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 3, 1, 1, 3)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setStyleSheet("QSpinBox {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.spinBox_2.setMaximum(9999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 4, 1, 1, 3)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("QSpinBox {\n"
"    color: black; /* 文本颜色为黑色 */\n"
"}\n"
"")
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 5, 1, 1, 3)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(710, 490, 202, 101))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton:hover {\n"
"    background-color: #0000FF; /* 鼠标悬停时的背景颜色为蓝色 */\n"
"    color: #FFFFFF; /* 鼠标悬停时的文字颜色为白色 */\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #0000FF; /* 鼠标悬停时的背景颜色为蓝色 */\n"
"    color: #FFFFFF; /* 鼠标悬停时的文字颜色为白色 */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Setting</p></body></html>"))
        self.label_7.setToolTip(_translate("MainWindow", "We can set where to save search database, vendor data file and yearly reports here"))
        self.label_7.setText(_translate("MainWindow", "Data folders directory"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Search database"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Vendor data file"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Yearly reports"))
        self.pushButton_2.setText(_translate("MainWindow", "Choose"))
        self.pushButton_4.setText(_translate("MainWindow", "Choose"))
        self.label_2.setToolTip(_translate("MainWindow", "The number of seconds the program will wait between sending each report request to a given vendor."))
        self.label_2.setText(_translate("MainWindow", "Report request interval"))
        self.label_3.setToolTip(_translate("MainWindow", "The number of seconds the program will allow a vendor to respond to each report request before cancelling it."))
        self.label_3.setText(_translate("MainWindow", "Request timeout"))
        self.label_4.setToolTip(_translate("MainWindow", "Can change if you find the load on your desktop is too high"))
        self.label_4.setText(_translate("MainWindow", "Concurrent vendors"))
        self.label_5.setToolTip(_translate("MainWindow", "The maximum number of reports to work on at the same time. If set too high, the UI might freeze while fetching reports but the fetching process will continue."))
        self.label_5.setText(_translate("MainWindow", "Concurrent reports"))
        self.label_6.setToolTip(_translate("MainWindow", "How program identifies itself to the SUSHI servers. Some vendors will reject some particular user agents. Only change this if there is a known problem as it will affect all requests to all vendors. "))
        self.label_6.setText(_translate("MainWindow", "User agent"))
        self.checkBox.setText(_translate("MainWindow", "Can vendor data be exported to clear text?"))
        self.label_8.setToolTip(_translate("MainWindow", "This is where the special and non-calendar-year data range reports will be saved"))
        self.label_8.setText(_translate("MainWindow", "Other reports directory"))
        self.pushButton_3.setText(_translate("MainWindow", "Rebuild Data Base"))
        self.pushButton.setText(_translate("MainWindow", "Save All Changes"))
import image_rc
