# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateDatabaseProgressDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_database_dialog(object):
    def setupUi(self, update_database_dialog):
        update_database_dialog.setObjectName("update_database_dialog")
        update_database_dialog.resize(433, 396)
        update_database_dialog.setStyleSheet("QDialog {\n"
"background-color: #323232;\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(update_database_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status_label = QtWidgets.QLabel(update_database_dialog)
        self.status_label.setStyleSheet("color: white;")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)
        self.progressbar = QtWidgets.QProgressBar(update_database_dialog)
        self.progressbar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    color: black;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"    width: 20px;\n"
"}")
        self.progressbar.setMaximum(100)
        self.progressbar.setProperty("value", 20)
        self.progressbar.setObjectName("progressbar")
        self.verticalLayout.addWidget(self.progressbar)
        self.scrollarea = QtWidgets.QScrollArea(update_database_dialog)
        self.scrollarea.setStyleSheet("\n"
"QWidget {\n"
"background-color: #2a2a2a;\n"
"border-radius: 4px;\n"
"color: white;\n"
"}")
        self.scrollarea.setWidgetResizable(True)
        self.scrollarea.setObjectName("scrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 264))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollarea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollarea)
        self.buttonBox = QtWidgets.QDialogButtonBox(update_database_dialog)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonBox.setBaseSize(QtCore.QSize(0, 0))
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStyleSheet("color: white;\n"
"border: 2px solid grey;\n"
"border-radius: 4px;\n"
"background-color: #000000;\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(update_database_dialog)
        self.buttonBox.accepted.connect(update_database_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(update_database_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(update_database_dialog)

    def retranslateUi(self, update_database_dialog):
        _translate = QtCore.QCoreApplication.translate
        update_database_dialog.setWindowTitle(_translate("update_database_dialog", "Update Database"))
        self.status_label.setText(_translate("update_database_dialog", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    update_database_dialog = QtWidgets.QDialog()
    ui = Ui_update_database_dialog()
    ui.setupUi(update_database_dialog)
    update_database_dialog.show()
    sys.exit(app.exec_())
